name: Markdown Linter
# Lint runs the markdown linter over all markdown files in the docs repository.
# This workflow is run on every pull request and push to main.
# The linter will pass without running if no *.md files have been changed.
on: 
  pull_request:
  push:
    branches:
      - main

jobs:
  markdown-lint:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - uses: nosborn/github-action-markdown-cli@v3.2.0
        with:
          files: .
          config_file: .markdownlint.yml
          # ignore_path: .markdownlintignore
